package/icu: Add support of ARC64 for double-conversion
    While building icu package in Buildroot (https://git.buildroot.org/buildroot/tree/package/icu)
    we're getting this (http://ru20arcgnu1:8080/?reason=icu-67-1):

    ------------------------------->8---------------------------
    double-conversion-utils.h:144:2: error: #error Target architecture was not detected as
    supported by Double-Conversion.
      144 | #error Target architecture was not detected as supported by Double-Conversion.
    ------------------------------->8---------------------------

    This patch adds ARC64 support for Double-Convertion to foss-for-synopsys-dwc-arc-processors/toolchain.
    When similar change will be added to google/double-conversion and unicode-org/icu
    this patch should be removed.

Signed-off-by: Veronika Kremneva <kremneva@synopsys.com>
Signed-off-by: Artem Panfilov <artemp@synopsys.com>